### ISSUE TITLE
Data loading 

### ISSUE THREAD

**Issue by rrawla** [sunnylqm/react-native-alphabetlistview#11]
Hi, 
I would like to thank you for doing such a great contribution to the community, I've one quick question 
I've a data list of json array object of 500 records which I'm trying to render with Alphabetlistview it renders fine but only shows 25 or 20 at a time when I click the alphabet , if I jump to M or Z it still loads data of A so I've to click like multiple times until it loads all the data and then it works normal ,**How can I load all the 500 records first and then enable section headers for clicking** , Is there a way to do that. Am I missing something..?

Any help is highly appreciated !!

Thanks!
Rahul

**Comment by sunnylqm** [comment]
500 is not a small number. So you may need carefully tweaking and still may not get a safisfying result.
I don't have much time to investigate, all I can suggest is to read the offical [ListView doc](http://facebook.github.io/react-native/docs/listview.html#content), and try to use some performance-related props(initialListSize , pageSize, etc) on AlphabetListview(they will be directly passed to the underlying ListView) to see a difference. And of course try to simplify you row structure.

**Comment by rrawla** [comment]
I figured it out.. thanks for the tip , I had to set the initialListSize property , that fixed it.

**Comment by joshbuchea** [comment]
@rrawla thanks for mentioning which prop resolved this for you. Saved me some time :smile:

**Comment by iniestano8** [comment]
@rrawla but this makes the page rendering slowly ...
