### ISSUE TITLE
undefined is not an object (evaluating 'sectionItem.measure')

### ISSUE THREAD

**Issue by porknoodles** [sunnylqm/react-native-alphabetlistview#31]
react-native-cli: 2.0.1
react-native: 0.36.1
"react-native-alphabetlistview": "^0.2.0"
node v6.10.2
npm 4.5.0

![image](https://cloud.githubusercontent.com/assets/18536089/25429180/c2e2b604-2aaa-11e7-8a01-88ffc5258eb0.png)

after searching through the error provided by the screenshot, i found out that i don't understand it at all.
`componentDidMount() {
    const sectionItem = this.refs.sectionItem0;

    this.measureTimer = setTimeout(() => {
      sectionItem.measure((x, y, width, height, pageX, pageY) => {
        //console.log([x, y, width, height, pageX, pageY]);
        this.measure = {
          y: pageY,
          height
        };
      })
    }, 0);

    //console.log(sectionItem);
  }`

i think that is what it meant right?
and I'm very sorry that i have to cover the project name....
project name....hmmm...rather not good to show in public

**Comment by ianhowe76** [comment]
Do you have the latest code from the repository?
There was a fix to check if the ref is undefined in this commit: https://github.com/sunnylqm/react-native-alphabetlistview/commit/d9c0727b95a787703b98a2b46f3e0fc750e9794f

Try setting your package.json value to https://github.com/sunnylqm/react-native-alphabetlistview.git and re-installing

**Comment by porknoodles** [comment]
thanks for replying
currently, I'm using this version "react-native-alphabetlistview": "^0.2.0"

i just copied pasted from [your link](https://github.com/sunnylqm/react-native-alphabetlistview/tree/master/components) to my node_module and it works.

may I know if it's because of wrong version?

**Comment by ianhowe76** [comment]
The current repository hasn't been published to npm unfortunately
