### ISSUE TITLE
Android alphabet clik scroll not working 

### ISSUE THREAD

**Issue by Jithinag007** [sunnylqm/react-native-alphabetlistview#35]
iphone is working pretty good but android device shows some issues. left side alphabet scroller not working

**Comment by podvipodvert** [comment]
+ for me too

**Comment by mag1492** [comment]
I have a similar issue when you don't fill all letters of the alphabet with items. You can scroll only to letter that contains value and the vertical scrollbar doesn't match the whole alphabet, hence why it seems like it's not working.

**Comment by mag1492** [comment]
It<s because the offset is not correct on android when it is not set at the start of the view. We need to use onLayout and check the firstItemSectionOffset from this event to set the maths properly.

**Comment by Jithinag007** [comment]
can you please share the codes

**Comment by Jithinag007** [comment]
Hi all get any solution ?

**Comment by Jithinag007** [comment]
on SelectableSectionsListView page 

if (!this.props.useDynamicHeights) {
      var cellHeight = this.props.cellHeight;
      var sectionHeaderHeight = this.props.sectionHeaderHeight;
      var keys = Object.keys(this.props.data);
      var index = keys.indexOf(section);

      var numcells = 0;
      for (var i = 0; i < index; i++) {
        numcells += this.props.data[keys[i]].length;
      }

      //sectionHeaderHeight = index * sectionHeaderHeight;
      y += numcells * cellHeight + sectionHeaderHeight;
      var maxY = this.totalHeight - this.containerHeight + headerHeight;
      y = y > maxY ? maxY : y;

      this.refs.listview.scrollTo({ x:0, y, animated: true });
    } else {
      // this breaks, if not all of the listview is pre-rendered!
      // UIManager.measure(this.cellTagMap[section], (x, y, w, h) => {
      //   y = y - this.props.sectionHeaderHeight;
      //   this.refs.listview.scrollTo({ x:0, y, animated: true });
      // });
      UIManager.measureLayout(this.cellTagMap[section], ReactNative.findNodeHandle(this.refs.listview), () => { }, (xx, yy, ww, hh) => {
        y = yy - this.props.sectionHeaderHeight;
        this.refs.listview.scrollTo({ x: 0, y, animated: true });
      });
    }

**Comment by sosokorn** [comment]
Hi all, I have one problem on scrolling by click on alphabet. It is not working ,so anyone has any ideas and code please share to me . Thank you all. I use android device.
