### ISSUE TITLE
I get an empty page when I try out the code

### ISSUE THREAD

**Issue by bozzmob** [sunnylqm/react-native-alphabetlistview#7]
Hi,

Steps I have followed-
```
npm install react-native-alphabetlistview  --save  
```

Used the code that is exposed in the README file in [index.android.js](https://github.com/bozzmob/React-Native-Alphabetical-ListView/blob/master/index.android.js)

Link to my Github [project](https://github.com/bozzmob/React-Native-Alphabetical-ListView) repo.

But, I what I see is an empty white page. What am I doing wrong?

**Comment by sunnylqm** [comment]
Use chrome to debug, and post error info here.

**Comment by bozzmob** [comment]
Sorry to bother you @sunnylqm there was some issue with "require". Fixed it. Thanks for your time :+1: :)
