### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by dheysonalves** [sunnylqm/react-native-alphabetlistview#73]
Hi, I am looking forward to using this repo in my repository. But not sure if it still has anyone maintaining. Based on long date open issues.

Can someone answer this?

Thanks.

**Comment by ianhowe76** [comment]
@Dheyson I have updated my project to use https://github.com/CoderJWYang/react-native-alphabet-sectionlist
Api is pretty similar

**Comment by dheysonalves** [comment]
Thanks @ianhowe76 , gonna check it out.
